### ISSUE TITLE
Critical bug

### ISSUE THREAD

**Issue by Fourmisain** [iCrazyBlaze/ElytraEject#1]
I had a quick look at the code and I'm pretty sure there's a critial bug here:

https://github.com/iCrazyBlaze/ElytraEject/blob/63b3f55c1dc435b88a127787f6c7d9b0f629506f/src/main/java/io/github/icrazyblaze/eject/mixin/ServerPlayerMixin.java#L25-L27

Since the mixin injects at `HEAD`, this cancels the whole `ServerPlayer.tick()` method e.g. when you're not wearing an Elytra or not pressing shift, which is pretty much always.

While testing I noticed that items `/give`n aren't synced properly with the client and Potions of Harming deal no damage to the player. Who knows what else this breaks.

Since I don't see any reason to cancel `ServerPlayer.tick()` at all, the fix should be to simply delete that part of code (and also the `cancellable`).

I'd also advise you to rename your mixin method name to something more meaningful like `cancelFlight`, `ejectElytra` or something, because the method name can appear e.g. in stack traces and `injected` doesn't tell which mod it is from or what the method actually does.

**Comment by btarg** [comment]
Thanks for telling me this! This was an experimental mod for me to test out mixins for the first time, so please excuse any terrible rookie mistakes. I'll fix this right away. I didn't see the notification (for some reason it never appeared on GitHub), sorry for the wait.
